### ISSUE TITLE
Not closing when exiting sway

### ISSUE THREAD

**Issue by Kagukara** [ErikReider/SwayAudioIdleInhibit#12] opened 2023-07-19 16:30 UTC
When I exit sway, `sway-audio-idle` is still running when I check the processes. So when I launch sway again after exiting there will be two `sway-audio-idle` processes running. I have tried doing what this person did, here's the [link](https://www.reddit.com/r/swaywm/comments/v0g2yo/how_to_exit_and_start_sway_again_without/) but it didn't work. Is there a way to close `sway-audio-idle` when exiting sway?

**Comment by ErikReider** [comment] 2023-07-19 17:06
This is not an issue caused by the project so I'll be closing this. 

What I do is to run `loginctl terminate-session self` which kills all of the processes :)

**Closed** 2023-07-19 17:06 UTC

**Comment by Kagukara** [comment] 2023-07-19 18:01
Thank you for the quick response and for a way to close `sway-audio-idle` when exiting sway.
